name: hcgcl
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4=py311haa95532_0
  - aiohttp=3.11.10=py311h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - attrs=24.3.0=py311haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311h57dcf0c_0
  - brotli-python=1.0.9=py311h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.6.15=h4c7d964_0
  - certifi=2025.6.15=py311haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py311haa95532_0
  - contourpy=1.3.1=py311h214f63a_0
  - copulas=0.12.3=pyhd8ed1ab_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.7.1=h8ddb27b_0
  - faiss=1.8.0=py311cuda120h46d8d5c_1_cuda
  - faiss-gpu=1.8.0=h3722977_2
  - filelock=3.17.0=py311haa95532_0
  - fonttools=4.55.3=py311h827c3e9_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - frozenlist=1.5.0=py311h827c3e9_0
  - fsspec=2025.3.2=py311hbc747e5_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.4.2=py311haa95532_0
  - jpeg=9e=h827c3e9_3
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.22=h5bf469e_0
  - libfaiss=1.8.0=cuda120h2ee710b_1_cuda
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=12_h13b7882_netlib
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libtiff=4.7.0=h404307b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.0=py311haa95532_0
  - matplotlib-base=3.10.0=py311he19b0ae_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.1.0=py311h827c3e9_0
  - narwhals=1.44.0=pyhe01879c_0
  - networkx=3.4.2=py311haa95532_0
  - numexpr=2.10.1=py311h4cd664f_0
  - numpy=1.25.0=py311hdab7c0b_0
  - numpy-base=1.25.0=py311hd01c5d8_0
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.5.0=ha4e3fda_1
  - pandas=2.2.3=py311h5da7b33_0
  - pillow=11.1.0=py311hea0d53e_1
  - pip=25.1=pyhc872135_2
  - plotly=6.2.0=pyhd8ed1ab_0
  - pot=0.9.5=py311hcf9f919_0
  - propcache=0.3.1=py311h827c3e9_0
  - psutil=5.9.0=py311h827c3e9_1
  - pyg=2.5.2=py311_torch_2.2.0_cu121
  - pyparsing=3.2.0=py311haa95532_0
  - pyqt=6.7.1=py311h5da7b33_1
  - pyqt6-sip=13.9.1=py311h827c3e9_1
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.2.2=py3.11_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311haa95532_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - qtbase=6.7.3=h0804d20_0
  - qtdeclarative=6.7.3=h5da7b33_0
  - qtsvg=6.7.3=hf2fb9eb_0
  - qttools=6.7.3=h0de5f00_0
  - qtwebchannel=6.7.3=h5da7b33_0
  - qtwebsockets=6.7.3=h5da7b33_0
  - requests=2.32.4=py311haa95532_0
  - scikit-learn=1.6.1=py311h585ebfc_0
  - scipy=1.15.3=py311h180bac5_0
  - setuptools=78.1.1=py311haa95532_0
  - sip=6.10.0=py311h5da7b33_0
  - six=1.17.0=py311haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - sympy=1.13.3=py311haa95532_1
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tk=8.6.14=h5e9d12e_1
  - tornado=6.5.1=py311h827c3e9_0
  - tqdm=4.67.1=py311h746a85d_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.20348.0=haa95532_0
  - unicodedata2=15.1.0=py311h827c3e9_1
  - urllib3=2.3.0=py311haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h818238b_26
  - vs2015_runtime=14.44.35208=h38c0c73_26
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.18.0=py311h827c3e9_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - aiobotocore==2.23.0
      - aioitertools==0.12.0
      - anndata==0.11.4
      - array-api-compat==1.12.0
      - asciitree==0.3.3
      - botocore==1.38.27
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2024.5.3
      - datashader==0.18.1
      - deprecated==1.2.18
      - docrep==0.3.2
      - fasteners==0.19
      - geopandas==1.1.0
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - igraph==0.11.9
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - inflect==7.5.0
      - ipython-genutils==0.2.0
      - jmespath==1.0.1
      - jupyterlab==4.4.3
      - jupyterlab-server==2.27.3
      - lazy-loader==0.4
      - leidenalg==0.10.2
      - llvmlite==0.44.0
      - locket==1.0.0
      - loompy==3.0.8
      - louvain==0.8.2
      - markdown-it-py==3.0.0
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.2
      - notebook==7.4.3
      - numba==0.61.2
      - numcodecs==0.15.1
      - numpy-groupies==0.11.3
      - ome-zarr==0.11.1
      - omnipath==1.0.10
      - opencv-python==4.11.0.86
      - packaging==25.0
      - param==2.2.1
      - partd==1.4.2
      - patsy==1.0.1
      - pims==0.7
      - pooch==1.8.2
      - pyarrow==20.0.0
      - pyct==0.5.0
      - pyogrio==0.11.0
      - pyproj==3.7.1
      - python-igraph==0.11.9
      - rich==14.0.0
      - rpy2==3.5.16
      - s3fs==2025.3.2
      - scikit-image==0.25.2
      - seaborn==0.13.2
      - shapely==2.1.1
      - slicerator==1.1.0
      - spatial-image==1.2.1
      - spatialdata==0.4.0
      - squidpy==1.6.5
      - statsmodels==0.14.4
      - texttable==1.7.0
      - tifffile==2025.6.11
      - toolz==1.0.0
      - torch-cluster==1.6.3+pt22cu121
      - torch-scatter==2.1.2+pt22cu121
      - torch-sparse==0.6.18+pt22cu121
      - torch-spline-conv==1.2.2+pt22cu121
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - typeguard==4.4.4
      - typing-extensions==4.14.0
      - tzlocal==5.3.1
      - validators==0.35.0
      - wrapt==1.17.2
      - xarray==2024.11.0
      - xarray-dataclasses==1.9.1
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - zarr==2.18.7
      - zipp==3.23.0
prefix: D:\SoftWare\anaconda\envs\hcgcl
